FROM debian:bullseye-slim
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y install \
    wget \
	bash \
	php \
	php-cgi \
	php-mysql \
	php-fpm \
	php-pdo \
	php-gd \
	php-cli \
	php-mbstring \
    curl
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp
RUN mkdir /run/php
COPY ./tools/setup.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/setup.sh
WORKDIR /var/www/html/
ENTRYPOINT [ "/usr/local/bin/setup.sh" ]
CMD [ "php-fpm7.4", "-F" ]

EXPOSE 9000
